spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jubi
    username: root
    password: 12345678
  redis:
    host: localhost
    port: 6379
    database: 3
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 要使用的模型ID
jubi:
  ai:
    model:
      model-id: 1659171950288818178
  thread:
    corePollSize: 2
    maximumPoolSize: 4
    keepAliveTime: 100
    queueCapacity: 4

yuapi:
  client:
    access-key: sytt8xli2cn9chufxkvm53ibo7w8d6vm
    secret-key: eolzbnjcwyrlt4wk5xziwk4yrn9m0p29