spring:
  application:
    name: jubi-backend
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）